apiVersion: v1
kind: Pod
metadata:
  labels:
     name: jenkins-yum-repo-updater-slave
spec:
  #serviceAccount: jenkins
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: repo-rpm-updater
      image: jportasa/repo-rpm-updater:1.0
      command: ["tail", "-f", "/dev/null"]
      tty: true
      imagePullPolicy: Always
      volumeMounts:
        - name: s3-shared
          mountPath: /data/
          mountPropagation: HostToContainer
    - name: s3fs
      image: josh9398/s3fs
      tty: true
      imagePullPolicy: Always
      securityContext:
        privileged: true
      env:
        - name: AWS_ACCESS_KEY_ID
          value: "AKIA54FIHR7BYCAJPGBE"
        - name: AWS_SECRET_ACCESS_KEY
          value: "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"
        - name: S3_BUCKET
          value: "nr-test"
        - name: MNT_POINT
          value: "/mnt"
        - name: S3_ENDPOINT
          value: "https://s3.amazonaws.com"
      volumeMounts:
        - name: s3-shared
          mountPath: /mnt
          mountPropagation: Bidirectional
      nodeSelector:
        kubernetes.io/os: "linux"
  volumes:
    - name: s3-shared
      emptyDir: {}

