apiVersion: v1
kind: Pod
metadata:
  labels:
     name: jenkins-repo-yum-updater-slave
spec:
  #serviceAccount: jenkins
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: repo-yum-updater
      image: jportasa/repo-yum-updater:1.0
      command: ["tail", "-f", "/dev/null"]
      tty: true
      imagePullPolicy: Always
      volumeMounts:
        - name: s3-shared
          mountPath: /data/
          mountPropagation: HostToContainer
    - name: s3fs
      image: jportasa/s3fs:1.0
      tty: true
      imagePullPolicy: Always
      securityContext:
        privileged: true
      env:
        - name: IAM_ROLE
          value: "nr-repo-yum-updater"
        - name: S3_BUCKET
          value: "nr-test"
        - name: MNT_POINT
          value: "/mnt"
        - name: S3_ENDPOINT
          value: "https://s3.amazonaws.com"
      volumeMounts:
        - name: s3-shared
          mountPath: /mnt
          mountPropagation: Bidirectional
      nodeSelector:
        kubernetes.io/os: "linux"
  volumes:
    - name: s3-shared
      emptyDir: {}

